In [1]:
import joblib

In [3]:
model = joblib.load("model.pkl")

In [4]:
model.predict([[13]])

array([147831.18221118])

In [5]:
joblib.load("training_data.pkl")

    YearsExperience
28             10.3
24              8.7
12              4.0
0               1.1
4               2.2
16              5.1
5               2.9
13              4.1
11              4.0
22              7.9
1               1.3
2               1.5
25              9.0
3               2.0
21              7.1
26              9.5
18              5.9
29             10.5
20              6.8
7               3.2
10              3.9
14              4.5
19              6.0
6               3.0
0              40.0
1              12.1
2              16.1
3              24.1
4              35.1
0              40.0
1              12.1
2              16.1
3              24.1
4              35.1
0              40.0
1              12.1
2              16.1
3              24.1
4              35.1
0              40.0
1              12.1
2              16.1
3              24.1
4              35.1
0              40.0
1              12.1
2              16.1
3              24.1
4              35.1